version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "kimlam2010"
    assignees:
      - "kimlam2010"
    milestone: "dependency-updates" 